package com.martin.ads.omoshiroilib.filter.helper;

/**
 * Created by Ads on 2017/2/13.
 */

public enum FilterType {
    //Pass Through
    NONE,

    //Beautify
    BEAUTIFY_A,

    //Effects
    GREEN_HOUSE_FILTER,
    BLACK_WHITE_FILTER,
    PAST_TIME_FILTER,
    MOON_LIGHT_FILTER,
    PRINTING_FILTER,
    TOY_FILTER,
    BRIGHTNESS_FILTER,
    VIGNETTE_FILTER,
    MULTIPLY_FILTER,
    REMINISCENCE_FILTER,
    SUNNY_FILTER,
    MX_LOMO_FILTER,
    SHIFT_COLOR_FILTER,
    MX_FACE_BEAUTY_FILTER,
    MX_PRO_FILTER,
    SPHERE_REFLECTOR,
    FILL_LIGHT_FILTER,

    //Image Processing : 2
    GRAY_SCALE,
    INVERT_COLOR,

    //Extended : 2
    BRA_SIZE_TEST_LEFT,
    BRA_SIZE_TEST_RIGHT,

    //ShaderToy : 20
    EDGE_DETECTION_FILTER,
    PIXELIZE_FILTER,
    EM_INTERFERENCE_FILTER,
    TRIANGLES_MOSAIC_FILTER,
    LEGOFIED_FILTER,
    TILE_MOSAIC_FILTER,
    BLUEORANGE_FILTER,
    CHROMATIC_ABERRATION_FILTER,
    BASICDEFORM_FILTER,
    CONTRAST_FILTER,
    NOISE_WARP_FILTER,
    REFRACTION_FILTER,
    MAPPING_FILTER,
    CROSSHATCH_FILTER,
    LICHTENSTEINESQUE_FILTER,
    ASCII_ART_FILTER,
    MONEY_FILTER,
    CRACKED_FILTER,
    POLYGONIZATION_FILTER,
    FAST_BLUR_FILTER,

}
